### ISSUE TITLE
Can't read property of code

### ISSUE THREAD

**Issue by ashwini0529** [aashrairavooru/VIT-Academics_CLI#4]
When we enter the command, it gives an error
here:   if (response.status.code !== 0)

**Comment by aashrairavooru** [comment]
Could you elaborate

**Comment by ashwini0529** [comment]
This is what I get on running the command checkAttendance : 
![selection_006](https://cloud.githubusercontent.com/assets/8419333/8613807/8a2899aa-2700-11e5-9255-54385b6f4906.png)

**Comment by aashrairavooru** [comment]
hmm seems like the response format has changed,let me see

**Comment by aashrairavooru** [comment]
can you do the curl calls as mentioned in this wiki https://github.com/aneesh-neelam/VITacademics/wiki/JSON-API, i kind of suspect its because there is no attendance because of the start of the sem,make sure you post the output here

**Comment by aashrairavooru** [comment]
![screenshot from 2015-07-10 14 27 47](https://cloud.githubusercontent.com/assets/7071610/8615412/e79d4644-270f-11e5-9708-a2fdabf4556c.png)
looks like VITAcademics is down for maintainence

**Comment by aashrairavooru** [comment]
i guess the api should handle situations like these and show the appropriate mesasge

**Comment by aneesh-neelam** [comment]
You're using the wrong API URL. It's https://vitacademics-rel.herokuapp.com/. 
The -dev one has been shut down and will be deleted soon.

**Comment by aashrairavooru** [comment]
oops i meant the app in the last comment,thanks for the heads up @aneesh-neelam

**Comment by ashwini0529** [comment]
@aashrairavooru , I think @aneesh-neelam  gave the solution..

**Comment by ashwini0529** [comment]
It's working now. :+1:

**Comment by aashrairavooru** [comment]
corrections included in v1.3.1

**Comment by ashwini0529** [comment]
Yeah I saw! Thanks! :)
